# Metrics Cops

Metrics/ClassLength:
  Description: 'Avoid classes longer than 100 lines of code.'
  Max: 100
  Enabled: true

Metrics/ModuleLength:
  Description: 'Avoid modules longer than 150 lines of code.'
  Max: 150
  Enabled: true

Metrics/ParameterLists:
  Description: 'Pass no more than four parameters into a method.'
  Max: 4
  Enabled: true

Metrics/MethodLength:
  Description: 'Avoid methods longer than 50 lines of code.'
  Max: 50
  Enabled: true

# Offense count: 2
# Configuration parameters: IgnoredMethods, CountRepeatedAttributes.
Metrics/AbcSize:
  Max: 28

Metrics/BlockLength:
  CountComments: false
  Max: 50
  IgnoredMethods:
    - context
    - describe
    - it
    - shared_examples
    - shared_examples_for
    - namespace
    - draw
    - configure
    - group
    - ActiveRecord::Schema.define

# Offense count: 2
# Configuration parameters: AllowedConstants.
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/**/*'
    - 'db/**/*'
    - 'config/application.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/**/*'

Layout/LineLength:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'

# Style/ClassAndModuleChildren:
#   Enabled: false
